#!/usr/bin/env npx ts-node
/**
 * 10x Marketing Team - Landing Page Deployment Script
 *
 * Scaffolds and deploys landing pages with best practices.
 *
 * Usage:
 *   npx ts-node scripts/deploy-landing.ts --template saas --name "product-launch"
 *   npx ts-node scripts/deploy-landing.ts --template leadgen --name "ebook-download"
 */

import * as fs from 'fs';
import * as path from 'path';

// =============================================================================
// TYPES
// =============================================================================

type Template = 'saas' | 'leadgen' | 'product-launch' | 'minimal';

interface PageConfig {
  name: string;
  template: Template;
  title: string;
  description: string;
  sections: string[];
}

// =============================================================================
// ARGUMENT PARSING
// =============================================================================

function parseArgs(): { template: Template; name: string; title?: string } {
  const args = process.argv.slice(2);
  const parsed: Record<string, string> = {};

  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--')) {
      const key = args[i].slice(2);
      const value = args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : '';
      parsed[key] = value;
      if (value) i++;
    }
  }

  if (!parsed.template || !['saas', 'leadgen', 'product-launch', 'minimal'].includes(parsed.template)) {
    console.error('Error: --template must be one of: saas, leadgen, product-launch, minimal');
    process.exit(1);
  }

  if (!parsed.name) {
    console.error('Error: --name is required');
    process.exit(1);
  }

  return {
    template: parsed.template as Template,
    name: parsed.name,
    title: parsed.title,
  };
}

// =============================================================================
// TEMPLATE GENERATORS
// =============================================================================

const TEMPLATE_CONFIGS: Record<Template, Omit<PageConfig, 'name'>> = {
  saas: {
    template: 'saas',
    title: 'SaaS Product Landing Page',
    description: 'Full-featured SaaS landing page with hero, features, pricing, and CTA',
    sections: ['Hero', 'Features', 'HowItWorks', 'Testimonials', 'Pricing', 'FAQ', 'CTA', 'Footer'],
  },
  leadgen: {
    template: 'leadgen',
    title: 'Lead Generation Landing Page',
    description: 'Conversion-focused page for capturing leads',
    sections: ['Hero', 'Benefits', 'SocialProof', 'LeadForm', 'Footer'],
  },
  'product-launch': {
    template: 'product-launch',
    title: 'Product Launch Landing Page',
    description: 'Exciting launch page with countdown and early access',
    sections: ['Hero', 'Countdown', 'Features', 'EarlyAccess', 'Footer'],
  },
  minimal: {
    template: 'minimal',
    title: 'Minimal Landing Page',
    description: 'Simple, focused landing page',
    sections: ['Hero', 'CTA', 'Footer'],
  },
};

function generatePageComponent(config: PageConfig): string {
  const componentName = config.name
    .split('-')
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');

  const imports = config.sections
    .map(s => `import ${s} from '@/components/landing/${s}';`)
    .join('\n');

  const components = config.sections
    .map(s => `        <${s} />`)
    .join('\n');

  return `/**
 * ${config.title}
 * Template: ${config.template}
 * Generated by 10x Marketing Team
 */

'use client';

${imports}
import AgentationFeedback from '@/components/feedback/AgentationFeedback';
import { useState } from 'react';

export default function ${componentName}Page() {
  const [feedbackMode, setFeedbackMode] = useState(false);

  return (
    <main className="relative min-h-screen bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900">
      {/* Background Effects */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-primary-500/20 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-accent-500/20 rounded-full blur-3xl" />
      </div>

      {/* Page Content */}
      <div className="relative z-10">
${components}
      </div>

      {/* Feedback Toggle */}
      <button
        onClick={() => setFeedbackMode(!feedbackMode)}
        className="fixed bottom-6 right-6 z-50 px-6 py-3 bg-gradient-to-r from-primary-500 to-accent-500 text-white font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all"
      >
        {feedbackMode ? 'Exit Feedback' : 'Give Feedback'}
      </button>

      {feedbackMode && <AgentationFeedback />}
    </main>
  );
}
`;
}

function generateRouteFile(name: string): string {
  return `/**
 * Route configuration for ${name}
 */

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${name.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' ')} | 10x Marketing',
  description: 'Generated landing page',
};

export { default } from './${name}';
`;
}

// =============================================================================
// FILE OPERATIONS
// =============================================================================

function createDirectory(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function writeFile(filePath: string, content: string): void {
  fs.writeFileSync(filePath, content);
  console.log(`  ✓ Created: ${filePath}`);
}

// =============================================================================
// MAIN
// =============================================================================

function main() {
  console.log('🚀 10x Marketing Team - Landing Page Generator\n');

  const args = parseArgs();
  const templateConfig = TEMPLATE_CONFIGS[args.template];

  const config: PageConfig = {
    ...templateConfig,
    name: args.name,
    title: args.title || templateConfig.title,
  };

  console.log(`Template: ${config.template}`);
  console.log(`Name: ${config.name}`);
  console.log(`Sections: ${config.sections.join(', ')}\n`);

  // Determine output directory
  const baseDir = process.cwd();
  const pagesDir = path.join(baseDir, 'src', 'app', config.name);

  console.log('Creating files...\n');

  // Create directory
  createDirectory(pagesDir);

  // Generate and write page component
  const pageContent = generatePageComponent(config);
  writeFile(path.join(pagesDir, `${config.name}.tsx`), pageContent);

  // Generate and write route file
  const routeContent = generateRouteFile(config.name);
  writeFile(path.join(pagesDir, 'page.tsx'), routeContent);

  console.log('\n✅ Landing page created successfully!\n');

  console.log('Next steps:');
  console.log(`  1. Run: npm run dev`);
  console.log(`  2. Visit: http://localhost:3000/${config.name}`);
  console.log(`  3. Click "Give Feedback" to add annotations`);
  console.log(`  4. Export feedback and process with: npx ts-node scripts/process-feedback.ts\n`);

  console.log('Missing components?');
  console.log('  The page references these section components:');
  config.sections.forEach(s => {
    console.log(`    - src/components/landing/${s}.tsx`);
  });
  console.log('\n  Create any missing components or copy from templates.');
}

main();
